### ISSUE TITLE
Is this repository open to everyone?

### ISSUE THREAD

**Issue by bipul-mohanto** [dsilvavinicius/rayvr#1]
Hi!
I would like to know, if this repository is open to everyone or only to the IMPA members? I would love to explore your improvement on Falcor for research purpose, if I may.

I tried to clone your github repository, however, it says `one or more projects in the solution were not loaded correctly`.

**Comment by dsilvavinicius** [comment]
Hello, Bipul.

This repository should not be public right now. We still need to prepare it to release for the public, since the code here is very experimental and it would be difficult to setup properly as it is.
